name: "Default" # gray

.base-style:
  shape:
    shape-type: "box"
    style: "filled"
    fillcolor: "lightgray"
  text:
    fontsize: 12
    fontname: "Courier"
    align: "center"
    color: "black"
    bgcolor: "lightgray"
    bold: false
    underlined: false
    italic: false

.entity-base:
  extends: .base-style

.entity-title:
  extends: .entity-base/text
  bgcolor: "darkgray"
  bold: true
  underlined: true

.entity-field:
  extends: .entity-base/text
  align: "left"
  fontsize: 10

.entity-primary-key:
  extends: .entity-base/text
  align: "left"
  bold: true

.entity-weak-base:
  extends: .entity-base
  shape:
    style: "filled,dashed"

.entity-weak-title:
  extends: .entity-weak-base/text
  bgcolor: "darkgray"
  bold: true
  underlined: true

.entity-weak-field:
  extends: .entity-weak-base/text
  align: "left"
  fontsize: 10

.entity-weak-primary-key:
  extends: .entity-weak-base/text
  align: "left"
  bold: true

.cluster-base:
  extends: .base-style/text
  color: "black"
  bgcolor: "white"
  fontsize: 14
  italic: true

.relationship-base:
  extends: .base-style
  shape:
    shape-type: "oval"
    fillcolor: "gray80"
  text:
    bgcolor: "gray80"

.relationship-title:
  extends: .relationship-base/text
  bold: true

.relationship-field:
  extends: .relationship-base/text
  fontsize: 10

.relationship-note:
  extends: .relationship-base
  shape:
    shape-type: "box"
    style: "dashed"
    fillcolor: "none"
  text:
    bgcolor: "none"
    italic: true

.relationship-cluster:
  extends: .relationship-base/shape
  shape-type: "polygon"
  style: "none"

style-sheet:
  entity:
    extends: .entity-base/shape
    title:
      extends: .entity-title
    field:
      extends: .entity-field
    primary-key:
      extends: .entity-primary-key

  cluster:
    extends: .cluster-base

  entity-weak:
    extends: .entity-weak-base/shape
    title:
      extends: .entity-weak-title
    field:
      extends: .entity-weak-field
    primary-key:
      extends: .entity-weak-primary-key

  relationship:
    extends: .relationship-base/shape
    title:
      extends: .relationship-title
    field:
      extends: .relationship-field
    note:
      extends: .relationship-note
    cluster:
      extends: .relationship-cluster
